package com.github.cloudcodec.core

import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType

data class TableInfo(val name: String, val columns: List<Column>)

data class Column(
    val name: String,
    val type: FullyQualifiedJavaType,
    val comment: String?,
    val primaryKey: Boolean,
    val autoGenerated: Boolean
)

abstract class OrmThing

data class MybatisPlusThing(
    val entity: MyClass,
    val mapper: MyClass,
    val dao: MyClass,
) : OrmThing()

data class JpaThing(
    val entity: MyClass,
    val repository: MyClass,
) : OrmThing() {
    lateinit var primaryKeyType: String
}

data class MyClass(
    val pkg: String,
    val className: String,
) {
    lateinit var content: String
}
