package com.github.cloudcodec.mybatisplus.intellij.core

import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType

data class TableInfo(val name: String, val columns: List<Column>)

data class Column(
    val name: String,
    val type: FullyQualifiedJavaType,
    val comment: String?,
    val primaryKey: Boolean,
    val autoGenerated: Boolean
)

data class MybatisPlusThing(
    val entity: MyClass,
    val mapper: MyClass,
    val dao: MyClass,
)

data class MyClass(
    val pkg: String,
    val className: String,
){
    lateinit var content: String
}
